// This file provides sample KPI data based on the backend/data files
// This is imported directly into the frontend for display

export const SAMPLE_KPIS = {
  product: [
    {
      id: 'product-1',
      department: 'Product',
      kpi_name: 'PEM Stack Units Shipped',
      category: 'Stack Performance',
      sn: 1,
      target_quarter: 450,
      actual_qtd: 418,
      target_q4: 150,
      actual_jan: 135,
      actual_feb: 142,
      actual_mar: 141,
      actual_q4: 418,
      progress: 'Y',
      commentary: 'On track to meet quarterly targets with slight variance in monthly distribution',
      financial_year: 'FY 2025',
    },
    {
      id: 'product-2',
      department: 'Product',
      kpi_name: 'Commercial Readiness Index',
      category: 'Product Maturity',
      sn: 2,
      target_quarter: 85,
      actual_qtd: 82,
      target_q4: 85,
      actual_jan: 78,
      actual_feb: 81,
      actual_mar: 82,
      actual_q4: 82,
      progress: 'Y',
      commentary: 'Steady improvement in product commercial readiness',
      financial_year: 'FY 2025',
    },
    {
      id: 'product-3',
      department: 'Product',
      kpi_name: 'System Efficiency %',
      category: 'Technical Performance',
      sn: 3,
      target_quarter: 92,
      actual_qtd: 89,
      target_q4: 92,
      actual_jan: 87,
      actual_feb: 88,
      actual_mar: 89,
      actual_q4: 89,
      progress: 'Y',
      commentary: 'Efficiency improvements ongoing, nearing target',
      financial_year: 'FY 2025',
    },
  ],
  sales: [
    {
      id: 'sales-1',
      department: 'Sales',
      kpi_name: 'Total Sales Pipeline Value',
      category: 'Revenue Realisation',
      sn: 1,
      target_quarter: 25000000,
      actual_qtd: 22500000,
      target_q4: 8500000,
      actual_jan: 7200000,
      actual_feb: 7800000,
      actual_mar: 7500000,
      actual_q4: 22500000,
      progress: 'Y',
      commentary: 'Strong pipeline development across all regions',
      financial_year: 'FY 2025',
    },
    {
      id: 'sales-2',
      department: 'Sales',
      kpi_name: 'Customer Acquisition (New)',
      category: 'Customer Growth',
      sn: 2,
      target_quarter: 15,
      actual_qtd: 12,
      target_q4: 5,
      actual_jan: 3,
      actual_feb: 4,
      actual_mar: 5,
      actual_q4: 12,
      progress: 'Y',
      commentary: 'New customer acquisition tracking well',
      financial_year: 'FY 2025',
    },
    {
      id: 'sales-3',
      department: 'Sales',
      kpi_name: 'BD Win Rate %',
      category: 'Sales Efficiency',
      sn: 3,
      target_quarter: 35,
      actual_qtd: 32,
      target_q4: 35,
      actual_jan: 30,
      actual_feb: 32,
      actual_mar: 34,
      actual_q4: 32,
      progress: 'Y',
      commentary: 'Win rate improving with better pipeline quality',
      financial_year: 'FY 2025',
    },
  ],
  marketing: [
    {
      id: 'marketing-1',
      department: 'Marketing',
      kpi_name: 'Brand Awareness Index',
      category: 'Brand Metrics',
      sn: 1,
      target_quarter: 75,
      actual_qtd: 72,
      target_q4: 75,
      actual_jan: 68,
      actual_feb: 70,
      actual_mar: 72,
      actual_q4: 72,
      progress: 'Y',
      commentary: 'Steady increase in brand visibility metrics',
      financial_year: 'FY 2025',
    },
    {
      id: 'marketing-2',
      department: 'Marketing',
      kpi_name: 'Website Traffic (Monthly)',
      category: 'Digital Engagement',
      sn: 2,
      target_quarter: 125000,
      actual_qtd: 118000,
      target_q4: 42000,
      actual_jan: 38000,
      actual_feb: 39000,
      actual_mar: 41000,
      actual_q4: 118000,
      progress: 'Y',
      commentary: 'Organic traffic growing month-over-month',
      financial_year: 'FY 2025',
    },
    {
      id: 'marketing-3',
      department: 'Marketing',
      kpi_name: 'Lead Generation (MQL)',
      category: 'Lead Quality',
      sn: 3,
      target_quarter: 450,
      actual_qtd: 425,
      target_q4: 150,
      actual_jan: 135,
      actual_feb: 140,
      actual_mar: 150,
      actual_q4: 425,
      progress: 'G',
      commentary: 'Exceeded lead quality targets this quarter',
      financial_year: 'FY 2025',
    },
  ],
  rnd: [
    {
      id: 'rnd-1',
      department: 'RnD',
      kpi_name: 'Technology Risk Reduction',
      category: 'Risk Management',
      sn: 1,
      target_quarter: 60,
      actual_qtd: 58,
      target_q4: 60,
      actual_jan: 50,
      actual_feb: 54,
      actual_mar: 58,
      actual_q4: 58,
      progress: 'Y',
      commentary: 'Continued progress in technology de-risking',
      financial_year: 'FY 2025',
    },
    {
      id: 'rnd-2',
      department: 'RnD',
      kpi_name: 'Patent Applications Filed',
      category: 'IP Development',
      sn: 2,
      target_quarter: 8,
      actual_qtd: 7,
      target_q4: 8,
      actual_jan: 2,
      actual_feb: 2,
      actual_mar: 3,
      actual_q4: 7,
      progress: 'Y',
      commentary: 'On track with IP filing objectives',
      financial_year: 'FY 2025',
    },
    {
      id: 'rnd-3',
      department: 'RnD',
      kpi_name: 'Product Iteration Cycles',
      category: 'Development Velocity',
      sn: 3,
      target_quarter: 4,
      actual_qtd: 4,
      target_q4: 4,
      actual_jan: 1,
      actual_feb: 1,
      actual_mar: 2,
      actual_q4: 4,
      progress: 'G',
      commentary: 'Exceeding development cycle targets',
      financial_year: 'FY 2025',
    },
  ],
  finance: [
    {
      id: 'finance-1',
      department: 'Finance',
      kpi_name: 'Gross Margin %',
      category: 'Profitability',
      sn: 1,
      target_quarter: 75,
      actual_qtd: 72.5,
      target_q4: 75,
      actual_jan: 71,
      actual_feb: 72,
      actual_mar: 73.5,
      actual_q4: 72.5,
      progress: 'Y',
      commentary: 'Margins improving with operational efficiency',
      financial_year: 'FY 2025',
    },
    {
      id: 'finance-2',
      department: 'Finance',
      kpi_name: 'Operating Expense Ratio',
      category: 'Cost Control',
      sn: 2,
      target_quarter: 105,
      actual_qtd: 102,
      target_q4: 105,
      actual_jan: 104,
      actual_feb: 103,
      actual_mar: 102,
      actual_q4: 102,
      progress: 'G',
      commentary: 'Better than budget OpEx management',
      financial_year: 'FY 2025',
    },
    {
      id: 'finance-3',
      department: 'Finance',
      kpi_name: 'Cash Runway (Months)',
      category: 'Cash Management',
      sn: 3,
      target_quarter: 24,
      actual_qtd: 28,
      target_q4: 24,
      actual_jan: 26,
      actual_feb: 27,
      actual_mar: 28,
      actual_q4: 28,
      progress: 'G',
      commentary: 'Excellent cash position exceeding targets',
      financial_year: 'FY 2025',
    },
  ],
};
