import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseKey = process.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error('❌ Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

// KPI Data Structure
const kpiData = {
  product_kpis: [
    // PRODUCT ENGINEERING - PEM Stack Performance (25kW)
    {
      department: 'Product',
      sub_department: 'PEM — Stack Performance (25kW)',
      month: 'January',
      year: 2026,
      kpi_name: 'Stack Efficiency',
      value: 'Not monitored for 5kW system',
      target: null,
      unit: '',
      category: 'Stack Performance',
    },
    {
      department: 'Product',
      sub_department: 'PEM — Stack Performance (25kW)',
      month: 'January',
      year: 2026,
      kpi_name: 'Voltage Efficiency',
      value: '100% efficiency at 1A/cm²',
      target: null,
      unit: '%',
      category: 'Stack Performance',
    },
    {
      department: 'Product',
      sub_department: 'PEM — Stack Performance (25kW)',
      month: 'January',
      year: 2026,
      kpi_name: 'Degradation Rate',
      value: '0% degradation in 48-hour steady state',
      target: null,
      unit: '%',
      category: 'Stack Performance',
    },
    {
      department: 'Product',
      sub_department: 'PEM — Stack Performance (25kW)',
      month: 'January',
      year: 2026,
      kpi_name: 'Hydrogen Purity',
      value: '99.9990',
      target: null,
      unit: '%',
      category: 'Stack Performance',
    },
    {
      department: 'Product',
      sub_department: 'PEM — Stack Performance (25kW)',
      month: 'January',
      year: 2026,
      kpi_name: 'Operating Pressure',
      value: '10 bar @ 400 Amps',
      target: null,
      unit: 'bar',
      category: 'Stack Performance',
    },
    // February
    {
      department: 'Product',
      sub_department: 'PEM — Stack Performance (25kW)',
      month: 'February',
      year: 2026,
      kpi_name: 'Stack Efficiency',
      value: '42',
      target: 48,
      unit: 'kWh/kg H₂',
      category: 'Stack Performance',
    },
    {
      department: 'Product',
      sub_department: 'PEM — Stack Performance (25kW)',
      month: 'February',
      year: 2026,
      kpi_name: 'Voltage Efficiency',
      value: '100',
      target: null,
      unit: '%',
      category: 'Stack Performance',
    },
    {
      department: 'Product',
      sub_department: 'PEM — Stack Performance (25kW)',
      month: 'February',
      year: 2026,
      kpi_name: 'Degradation Rate',
      value: '0',
      target: null,
      unit: '% degradation after 300 hours',
      category: 'Stack Performance',
    },
    {
      department: 'Product',
      sub_department: 'PEM — Stack Performance (25kW)',
      month: 'February',
      year: 2026,
      kpi_name: 'Hydrogen Purity',
      value: '99.999',
      target: null,
      unit: '%',
      category: 'Stack Performance',
    },
    {
      department: 'Product',
      sub_department: 'PEM — Stack Performance (25kW)',
      month: 'February',
      year: 2026,
      kpi_name: 'Operating Pressure',
      value: '15 bar @ 450 Amps',
      target: null,
      unit: 'bar',
      category: 'Stack Performance',
    },
    // PRODUCT ENGINEERING — MANUFACTURING
    {
      department: 'Product',
      sub_department: 'Manufacturing',
      month: 'January',
      year: 2026,
      kpi_name: 'Commercial Systems Built',
      value: '2',
      target: null,
      unit: 'units',
      category: 'Manufacturing',
    },
    {
      department: 'Product',
      sub_department: 'Manufacturing',
      month: 'January',
      year: 2026,
      kpi_name: 'Manufacturing Cost per kW',
      value: 'To be monitored',
      target: null,
      unit: '$/kW',
      category: 'Manufacturing',
    },
    {
      department: 'Product',
      sub_department: 'Manufacturing',
      month: 'January',
      year: 2026,
      kpi_name: 'Manufacturing Yield',
      value: '100',
      target: null,
      unit: '%',
      category: 'Manufacturing',
    },
    {
      department: 'Product',
      sub_department: 'Manufacturing',
      month: 'February',
      year: 2026,
      kpi_name: 'Commercial Systems Built',
      value: '5',
      target: 10,
      unit: 'units',
      category: 'Manufacturing',
    },
    {
      department: 'Product',
      sub_department: 'Manufacturing',
      month: 'February',
      year: 2026,
      kpi_name: 'Manufacturing Cost per kW',
      value: 'To be monitored',
      target: null,
      unit: '$/kW',
      category: 'Manufacturing',
    },
    {
      department: 'Product',
      sub_department: 'Manufacturing',
      month: 'February',
      year: 2026,
      kpi_name: 'Manufacturing Yield',
      value: '100',
      target: null,
      unit: '%',
      category: 'Manufacturing',
    },
    // PRODUCT — 250kW PLATFORM
    {
      department: 'Product',
      sub_department: '250kW Platform',
      month: 'January',
      year: 2026,
      kpi_name: 'Stack Architecture Freeze',
      value: '100',
      target: null,
      unit: '%',
      category: 'Platform Development',
    },
    {
      department: 'Product',
      sub_department: '250kW Platform',
      month: 'January',
      year: 2026,
      kpi_name: 'BOM Cost Model Completeness',
      value: '50',
      target: 70,
      unit: '%',
      category: 'Platform Development',
    },
    {
      department: 'Product',
      sub_department: '250kW Platform',
      month: 'January',
      year: 2026,
      kpi_name: 'Manufacturing Process Readiness',
      value: '25',
      target: null,
      unit: '%',
      category: 'Platform Development',
    },
    {
      department: 'Product',
      sub_department: '250kW Platform',
      month: 'February',
      year: 2026,
      kpi_name: 'Stack Architecture Freeze',
      value: '100',
      target: null,
      unit: '%',
      category: 'Platform Development',
    },
    {
      department: 'Product',
      sub_department: '250kW Platform',
      month: 'February',
      year: 2026,
      kpi_name: 'BOM Cost Model Completeness',
      value: '70',
      target: null,
      unit: '%',
      category: 'Platform Development',
    },
    {
      department: 'Product',
      sub_department: '250kW Platform',
      month: 'February',
      year: 2026,
      kpi_name: 'Manufacturing Process Readiness',
      value: '40',
      target: null,
      unit: '%',
      category: 'Platform Development',
    },
    // AEM STACK
    {
      department: 'Product',
      sub_department: 'AEM Stack',
      month: 'January',
      year: 2026,
      kpi_name: 'Stack Efficiency',
      value: '65.75',
      target: 60,
      unit: 'kWh/kg',
      category: 'AEM Stack',
    },
    {
      department: 'Product',
      sub_department: 'AEM Stack',
      month: 'January',
      year: 2026,
      kpi_name: 'Current Density',
      value: '0.7',
      target: null,
      unit: 'A/cm²',
      category: 'AEM Stack',
    },
    {
      department: 'Product',
      sub_department: 'AEM Stack',
      month: 'January',
      year: 2026,
      kpi_name: 'Operating Pressure',
      value: '1',
      target: null,
      unit: 'bar',
      category: 'AEM Stack',
    },
    {
      department: 'Product',
      sub_department: 'AEM Stack',
      month: 'January',
      year: 2026,
      kpi_name: 'Manufacturing Cost',
      value: '1126',
      target: null,
      unit: '$/kW',
      category: 'AEM Stack',
    },
    {
      department: 'Product',
      sub_department: 'AEM Stack',
      month: 'February',
      year: 2026,
      kpi_name: 'Stack Efficiency',
      value: '65.75',
      target: null,
      unit: 'kWh/kg',
      category: 'AEM Stack',
    },
    {
      department: 'Product',
      sub_department: 'AEM Stack',
      month: 'February',
      year: 2026,
      kpi_name: 'Current Density',
      value: '0.7',
      target: null,
      unit: 'A/cm²',
      category: 'AEM Stack',
    },
    {
      department: 'Product',
      sub_department: 'AEM Stack',
      month: 'February',
      year: 2026,
      kpi_name: 'Operating Pressure',
      value: '1',
      target: null,
      unit: 'bar',
      category: 'AEM Stack',
    },
    {
      department: 'Product',
      sub_department: 'AEM Stack',
      month: 'February',
      year: 2026,
      kpi_name: 'Manufacturing Cost',
      value: '1126',
      target: null,
      unit: '$/kW',
      category: 'AEM Stack',
    },
    {
      department: 'Product',
      sub_department: 'AEM Stack',
      month: 'February',
      year: 2026,
      kpi_name: 'Manufacturing Yield',
      value: 'Not established',
      target: null,
      unit: '',
      category: 'AEM Stack',
    },
  ],
  sales_kpis: [
    // DELIVERY & CUSTOMER OPERATIONS
    {
      department: 'Sales',
      sub_department: 'Delivery & Customer Operations',
      month: 'January',
      year: 2026,
      kpi_name: 'Commercial Systems Delivered',
      value: '1',
      target: 11,
      unit: 'units',
      category: 'Delivery',
    },
    {
      department: 'Sales',
      sub_department: 'Delivery & Customer Operations',
      month: 'January',
      year: 2026,
      kpi_name: 'On-time Delivery',
      value: '25',
      target: null,
      unit: '%',
      category: 'Delivery',
    },
    {
      department: 'Sales',
      sub_department: 'Delivery & Customer Operations',
      month: 'January',
      year: 2026,
      kpi_name: 'First-time Acceptance',
      value: '100',
      target: null,
      unit: '%',
      category: 'Delivery',
    },
    {
      department: 'Sales',
      sub_department: 'Delivery & Customer Operations',
      month: 'January',
      year: 2026,
      kpi_name: 'Order-to-Delivery Cycle',
      value: '60',
      target: null,
      unit: 'days',
      category: 'Delivery',
    },
    {
      department: 'Sales',
      sub_department: 'Delivery & Customer Operations',
      month: 'January',
      year: 2026,
      kpi_name: 'Post-delivery Issues per System',
      value: '1',
      target: null,
      unit: 'count',
      category: 'Delivery',
    },
    {
      department: 'Sales',
      sub_department: 'Delivery & Customer Operations',
      month: 'January',
      year: 2026,
      kpi_name: 'Critical Customer Issues',
      value: '1',
      target: null,
      unit: 'count',
      category: 'Delivery',
    },
    {
      department: 'Sales',
      sub_department: 'Delivery & Customer Operations',
      month: 'January',
      year: 2026,
      kpi_name: 'Mean Time to Resolution',
      value: 'Rectification in progress',
      target: null,
      unit: '',
      category: 'Delivery',
    },
    {
      department: 'Sales',
      sub_department: 'Delivery & Customer Operations',
      month: 'January',
      year: 2026,
      kpi_name: 'Customer Satisfaction',
      value: 'Not measured',
      target: null,
      unit: '',
      category: 'Delivery',
    },
    // February
    {
      department: 'Sales',
      sub_department: 'Delivery & Customer Operations',
      month: 'February',
      year: 2026,
      kpi_name: 'Commercial Systems Delivered',
      value: '1',
      target: null,
      unit: 'units',
      category: 'Delivery',
    },
    {
      department: 'Sales',
      sub_department: 'Delivery & Customer Operations',
      month: 'February',
      year: 2026,
      kpi_name: 'On-time Delivery',
      value: '0',
      target: null,
      unit: '%',
      category: 'Delivery',
    },
    {
      department: 'Sales',
      sub_department: 'Delivery & Customer Operations',
      month: 'February',
      year: 2026,
      kpi_name: 'First-time Acceptance',
      value: '100',
      target: null,
      unit: '%',
      category: 'Delivery',
    },
    {
      department: 'Sales',
      sub_department: 'Delivery & Customer Operations',
      month: 'February',
      year: 2026,
      kpi_name: 'Order-to-Delivery Cycle',
      value: '60',
      target: null,
      unit: 'days',
      category: 'Delivery',
    },
    {
      department: 'Sales',
      sub_department: 'Delivery & Customer Operations',
      month: 'February',
      year: 2026,
      kpi_name: 'Post-delivery Issues per System',
      value: '1',
      target: null,
      unit: 'count',
      category: 'Delivery',
    },
    {
      department: 'Sales',
      sub_department: 'Delivery & Customer Operations',
      month: 'February',
      year: 2026,
      kpi_name: 'Critical Customer Issues',
      value: '1',
      target: null,
      unit: 'count',
      category: 'Delivery',
    },
    {
      department: 'Sales',
      sub_department: 'Delivery & Customer Operations',
      month: 'February',
      year: 2026,
      kpi_name: 'Mean Time to Resolution',
      value: '3',
      target: null,
      unit: 'days',
      category: 'Delivery',
    },
    {
      department: 'Sales',
      sub_department: 'Delivery & Customer Operations',
      month: 'February',
      year: 2026,
      kpi_name: 'Customer Satisfaction',
      value: 'Not measured',
      target: null,
      unit: '',
      category: 'Delivery',
    },
  ],
  finance_kpis: [
    // FINANCE
    {
      department: 'Finance',
      sub_department: 'Finance',
      month: 'January',
      year: 2026,
      kpi_name: 'Cash Balance',
      value: '3540004',
      target: null,
      unit: '$',
      category: 'Financial',
    },
    {
      department: 'Finance',
      sub_department: 'Finance',
      month: 'January',
      year: 2026,
      kpi_name: 'Working Capital Movement',
      value: '-60561',
      target: null,
      unit: '$',
      category: 'Financial',
    },
    {
      department: 'Finance',
      sub_department: 'Finance',
      month: 'January',
      year: 2026,
      kpi_name: 'Operating Burn',
      value: 'Still in process',
      target: null,
      unit: '$',
      category: 'Financial',
    },
    {
      department: 'Finance',
      sub_department: 'Finance',
      month: 'January',
      year: 2026,
      kpi_name: 'Runway',
      value: 'Still in process',
      target: null,
      unit: 'months',
      category: 'Financial',
    },
    {
      department: 'Finance',
      sub_department: 'Finance',
      month: 'January',
      year: 2026,
      kpi_name: 'Non-dilutive Funding',
      value: '0',
      target: null,
      unit: '$',
      category: 'Financial',
    },
  ],
  marketing_kpis: [
    // MARKETING
    {
      department: 'Marketing',
      sub_department: 'Marketing',
      month: 'January',
      year: 2026,
      kpi_name: 'Qualified Inbound Inquiries',
      value: '11',
      target: 50,
      unit: 'count',
      category: 'Lead Generation',
    },
    {
      department: 'Marketing',
      sub_department: 'Marketing',
      month: 'January',
      year: 2026,
      kpi_name: 'Inbound from Priority ICP',
      value: '0',
      target: null,
      unit: '%',
      category: 'Lead Generation',
    },
    {
      department: 'Marketing',
      sub_department: 'Marketing',
      month: 'January',
      year: 2026,
      kpi_name: 'Inbound Accepted by Sales',
      value: '4',
      target: null,
      unit: '%',
      category: 'Lead Generation',
    },
    {
      department: 'Marketing',
      sub_department: 'Marketing',
      month: 'January',
      year: 2026,
      kpi_name: 'Inbound Response Time',
      value: 'Not measured',
      target: null,
      unit: 'hours',
      category: 'Lead Generation',
    },
    {
      department: 'Marketing',
      sub_department: 'Marketing',
      month: 'January',
      year: 2026,
      kpi_name: 'MQL → SQL Conversion',
      value: '0',
      target: null,
      unit: '%',
      category: 'Lead Generation',
    },
    {
      department: 'Marketing',
      sub_department: 'Marketing',
      month: 'January',
      year: 2026,
      kpi_name: 'Marketing-Sourced Pipeline',
      value: 'Not reported',
      target: null,
      unit: '$',
      category: 'Lead Generation',
    },
    // February
    {
      department: 'Marketing',
      sub_department: 'Marketing',
      month: 'February',
      year: 2026,
      kpi_name: 'Qualified Inbound Inquiries',
      value: '7',
      target: null,
      unit: 'count',
      category: 'Lead Generation',
    },
    {
      department: 'Marketing',
      sub_department: 'Marketing',
      month: 'February',
      year: 2026,
      kpi_name: 'Inbound from Priority ICP',
      value: '20',
      target: null,
      unit: '%',
      category: 'Lead Generation',
    },
    {
      department: 'Marketing',
      sub_department: 'Marketing',
      month: 'February',
      year: 2026,
      kpi_name: 'Inbound Accepted by Sales',
      value: '0',
      target: null,
      unit: '%',
      category: 'Lead Generation',
    },
    {
      department: 'Marketing',
      sub_department: 'Marketing',
      month: 'February',
      year: 2026,
      kpi_name: 'Inbound Response Time',
      value: 'Nil',
      target: null,
      unit: 'hours',
      category: 'Lead Generation',
    },
    {
      department: 'Marketing',
      sub_department: 'Marketing',
      month: 'February',
      year: 2026,
      kpi_name: 'MQL → SQL Conversion',
      value: '0',
      target: null,
      unit: '%',
      category: 'Lead Generation',
    },
    {
      department: 'Marketing',
      sub_department: 'Marketing',
      month: 'February',
      year: 2026,
      kpi_name: 'Marketing-Sourced Pipeline',
      value: '1.37',
      target: null,
      unit: '$M',
      category: 'Lead Generation',
    },
  ],
  rnd_kpis: [
    // R&D
    {
      department: 'RnD',
      sub_department: 'R&D',
      month: 'January',
      year: 2026,
      kpi_name: 'Catalyst Milestone Progress',
      value: '10',
      target: null,
      unit: '%',
      category: 'Development',
    },
    {
      department: 'RnD',
      sub_department: 'R&D',
      month: 'January',
      year: 2026,
      kpi_name: 'Membrane Milestone Progress',
      value: '15',
      target: null,
      unit: '%',
      category: 'Development',
    },
    {
      department: 'RnD',
      sub_department: 'R&D',
      month: 'January',
      year: 2026,
      kpi_name: 'MEA Milestone Progress',
      value: '30',
      target: null,
      unit: '%',
      category: 'Development',
    },
    {
      department: 'RnD',
      sub_department: 'R&D',
      month: 'January',
      year: 2026,
      kpi_name: 'Patent Families',
      value: '4 families / 9 submissions',
      target: null,
      unit: 'count',
      category: 'Development',
    },
    {
      department: 'RnD',
      sub_department: 'R&D',
      month: 'January',
      year: 2026,
      kpi_name: 'New IP Filings',
      value: 'Drafting in progress',
      target: null,
      unit: 'count',
      category: 'Development',
    },
    {
      department: 'RnD',
      sub_department: 'R&D',
      month: 'January',
      year: 2026,
      kpi_name: 'Grant Milestone Progress',
      value: '~200 hours testing',
      target: null,
      unit: 'hours',
      category: 'Development',
    },
    {
      department: 'RnD',
      sub_department: 'R&D',
      month: 'January',
      year: 2026,
      kpi_name: 'Future Option Programs',
      value: 'RFC — MEA Development',
      target: null,
      unit: '',
      category: 'Development',
    },
    // February
    {
      department: 'RnD',
      sub_department: 'R&D',
      month: 'February',
      year: 2026,
      kpi_name: 'Grant Milestone Progress',
      value: 'No progress due to space constraint',
      target: null,
      unit: 'hours',
      category: 'Development',
    },
  ],
  sales_bd_kpis: [
    // BUSINESS DEVELOPMENT — MENA
    {
      department: 'Sales',
      sub_department: 'Business Development — MENA',
      month: 'January',
      year: 2026,
      kpi_name: 'Qualified Enterprise Conversations',
      value: '1',
      target: 15,
      unit: 'count',
      category: 'BD',
    },
    {
      department: 'Sales',
      sub_department: 'Business Development — MENA',
      month: 'January',
      year: 2026,
      kpi_name: 'Anchor Accounts Identified',
      value: '0',
      target: null,
      unit: 'count',
      category: 'BD',
    },
    {
      department: 'Sales',
      sub_department: 'Business Development — MENA',
      month: 'January',
      year: 2026,
      kpi_name: 'Stakeholder Coverage',
      value: '0',
      target: null,
      unit: 'count',
      category: 'BD',
    },
    {
      department: 'Sales',
      sub_department: 'Business Development — MENA',
      month: 'January',
      year: 2026,
      kpi_name: 'Validated Use Cases',
      value: '0',
      target: null,
      unit: 'count',
      category: 'BD',
    },
    {
      department: 'Sales',
      sub_department: 'Business Development — MENA',
      month: 'January',
      year: 2026,
      kpi_name: 'Customer Readiness Assessments',
      value: '0',
      target: null,
      unit: 'count',
      category: 'BD',
    },
    {
      department: 'Sales',
      sub_department: 'Business Development — MENA',
      month: 'January',
      year: 2026,
      kpi_name: 'Pre-qualified Opportunities',
      value: '0',
      target: null,
      unit: 'count',
      category: 'BD',
    },
    {
      department: 'Sales',
      sub_department: 'Business Development — MENA',
      month: 'January',
      year: 2026,
      kpi_name: 'Technical Feasibility Checkpoints',
      value: '0',
      target: null,
      unit: 'count',
      category: 'BD',
    },
    {
      department: 'Sales',
      sub_department: 'Business Development — MENA',
      month: 'January',
      year: 2026,
      kpi_name: 'Local Ecosystem Mapping',
      value: 'UAE & Oman in progress',
      target: null,
      unit: '',
      category: 'BD',
    },
  ],
};

async function upsertKPIs() {
  try {
    console.log('🚀 Starting KPI data upsert...\n');

    // Upsert each table
    const tables = [
      { name: 'product_kpis', data: kpiData.product_kpis },
      { name: 'sales_kpis', data: [...kpiData.sales_kpis, ...kpiData.sales_bd_kpis] },
      { name: 'marketing_kpis', data: kpiData.marketing_kpis },
      { name: 'rnd_kpis', data: kpiData.rnd_kpis },
      { name: 'finance_kpis', data: kpiData.finance_kpis },
    ];

    for (const table of tables) {
      console.log(`📊 Processing ${table.name}...`);
      
      if (table.data.length === 0) {
        console.log(`   ⏭️  No data for ${table.name}\n`);
        continue;
      }

      // Batch insert
      const batchSize = 50;
      for (let i = 0; i < table.data.length; i += batchSize) {
        const batch = table.data.slice(i, i + batchSize);
        
        // Add default values for required columns if missing
        const processedBatch = batch.map(row => ({
          ...row,
          current_month: row.month,
          current_month_actual: typeof row.value === 'number' ? row.value : null,
          current_month_target: row.target,
          financial_year: `FY ${row.year}`,
          category: row.category || 'General',
        }));

        const { error } = await supabase
          .from(table.name)
          .upsert(processedBatch, {
            onConflict: 'kpi_name,month,year',
          });

        if (error) {
          console.error(`   ❌ Error in batch ${Math.floor(i / batchSize) + 1}:`, error);
        } else {
          console.log(`   ✓ Upserted ${batch.length} records (batch ${Math.floor(i / batchSize) + 1})`);
        }
      }

      console.log(`   ✅ Completed ${table.name}\n`);
    }

    console.log('✅ All KPI data upserted successfully!');
  } catch (err) {
    console.error('Fatal error:', err);
    process.exit(1);
  }
}

upsertKPIs().catch(console.error);
